# Generated by Django 5.2.15 on 2026-06-25 12:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('seat', 'Seat clears'), ('fare', 'Fare drops')], max_length=8)),
                ('train_number', models.CharField(max_length=16)),
                ('train_name', models.CharField(blank=True, default='', max_length=120)),
                ('from_code', models.CharField(max_length=12)),
                ('to_code', models.CharField(max_length=12)),
                ('journey_date', models.DateField()),
                ('travel_class', models.CharField(max_length=4)),
                ('quota', models.CharField(default='GN', max_length=4)),
                ('threshold', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('triggered', 'Triggered'), ('expired', 'Expired')], default='active', max_length=10)),
                ('last_value', models.CharField(blank=True, default='', max_length=40)),
                ('last_checked', models.DateTimeField(blank=True, null=True)),
                ('triggered_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]