# Generated by Django 5.2.15 on 2026-06-14 16:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Train',
            fields=[
                ('number', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('train_type', models.CharField(blank=True, max_length=40)),
                ('runs_on', models.CharField(default='1111111', max_length=7)),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='trains_to', to='stations.station')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='trains_from', to='stations.station')),
            ],
            options={
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='Stop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.PositiveIntegerField()),
                ('arrival', models.TimeField(blank=True, null=True)),
                ('departure', models.TimeField(blank=True, null=True)),
                ('day_offset', models.PositiveIntegerField(default=0)),
                ('distance_km', models.PositiveIntegerField(default=0)),
                ('platform', models.CharField(blank=True, max_length=10)),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stops', to='stations.station')),
                ('train', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stops', to='trains.train')),
            ],
            options={
                'ordering': ['train', 'sequence'],
            },
        ),
        migrations.CreateModel(
            name='Fare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('travel_class', models.CharField(choices=[('1A', 'AC First Class'), ('2A', 'AC 2 Tier'), ('3A', 'AC 3 Tier'), ('SL', 'Sleeper'), ('CC', 'AC Chair Car'), ('2S', 'Second Sitting')], max_length=2)),
                ('base_fare', models.DecimalField(decimal_places=2, max_digits=8)),
                ('train', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fares', to='trains.train')),
            ],
        ),
        migrations.CreateModel(
            name='Availability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('journey_date', models.DateField()),
                ('travel_class', models.CharField(choices=[('1A', 'AC First Class'), ('2A', 'AC 2 Tier'), ('3A', 'AC 3 Tier'), ('SL', 'Sleeper'), ('CC', 'AC Chair Car'), ('2S', 'Second Sitting')], max_length=2)),
                ('quota', models.CharField(choices=[('GN', 'General'), ('TQ', 'Tatkal'), ('LD', 'Ladies'), ('SS', 'Senior Citizen')], default='GN', max_length=2)),
                ('available', models.IntegerField(default=0)),
                ('waitlist', models.IntegerField(default=0)),
                ('train', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availability', to='trains.train')),
            ],
            options={
                'verbose_name_plural': 'availability',
            },
        ),
        migrations.AddIndex(
            model_name='train',
            index=models.Index(fields=['name'], name='trains_trai_name_f82357_idx'),
        ),
        migrations.AddIndex(
            model_name='stop',
            index=models.Index(fields=['station'], name='trains_stop_station_469288_idx'),
        ),
        migrations.AddConstraint(
            model_name='stop',
            constraint=models.UniqueConstraint(fields=('train', 'sequence'), name='uniq_train_sequence'),
        ),
        migrations.AddConstraint(
            model_name='stop',
            constraint=models.UniqueConstraint(fields=('train', 'station'), name='uniq_train_station'),
        ),
        migrations.AddConstraint(
            model_name='fare',
            constraint=models.UniqueConstraint(fields=('train', 'travel_class'), name='uniq_train_class_fare'),
        ),
        migrations.AddIndex(
            model_name='availability',
            index=models.Index(fields=['train', 'journey_date'], name='trains_avai_train_i_1a79bb_idx'),
        ),
        migrations.AddConstraint(
            model_name='availability',
            constraint=models.UniqueConstraint(fields=('train', 'journey_date', 'travel_class', 'quota'), name='uniq_availability_slot'),
        ),
    ]
