# Generated by Django 5.2.15 on 2026-06-15 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trains', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='availability',
            name='rac',
            field=models.IntegerField(default=0),
        ),
    ]
