# Generated by Django 5.2.15 on 2026-07-03 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trains', '0002_availability_rac'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stop',
            name='platform',
            field=models.CharField(blank=True, max_length=16),
        ),
        migrations.AlterField(
            model_name='train',
            name='number',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
    ]
