"""Downloadable PDF timetable for a train: every stop with arr/dep/halt."""

import io

from django.http import HttpResponse
from reportlab.lib import colors
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
from reportlab.lib.units import mm
from reportlab.platypus import (Paragraph, SimpleDocTemplate, Spacer, Table,
                                TableStyle)
from rest_framework.permissions import AllowAny
from rest_framework.views import APIView

from .models import Train
from .layout import platform_for

NAVY = colors.HexColor("#16224a")
AMBER = colors.HexColor("#e08a1e")
LINE = colors.HexColor("#d7dce6")
MUTED = colors.HexColor("#6b7488")
SOFT = colors.HexColor("#f3f5fb")

_DAYS = ["Mon", "Tue", "Wed", "Thu", "Fri", "Sat", "Sun"]


def _run_days(runs_on):
    flags = (runs_on or "1111111").ljust(7, "0")[:7]
    on = [_DAYS[i] for i, f in enumerate(flags) if f == "1"]
    if len(on) == 7:
        return "Daily"
    return ", ".join(on) if on else "—"


def _hhmm(t):
    return t.strftime("%H:%M") if t else "—"


def _halt(arr, dep):
    if not arr or not dep:
        return "—"
    a = arr.hour * 60 + arr.minute
    d = dep.hour * 60 + dep.minute
    mins = d - a
    if mins <= 0:
        return "—"
    return f"{mins} min"


def build_schedule_pdf(train):
    buf = io.BytesIO()
    doc = SimpleDocTemplate(
        buf, pagesize=A4,
        leftMargin=16 * mm, rightMargin=16 * mm,
        topMargin=16 * mm, bottomMargin=16 * mm,
        title=f"{train.number} schedule",
    )
    styles = getSampleStyleSheet()
    h_brand = ParagraphStyle("brand", parent=styles["Normal"], fontName="Helvetica-Bold",
                             fontSize=15, textColor=NAVY)
    h_title = ParagraphStyle("title", parent=styles["Normal"], fontName="Helvetica-Bold",
                             fontSize=13, textColor=NAVY, spaceBefore=2)
    sub = ParagraphStyle("sub", parent=styles["Normal"], fontName="Helvetica",
                        fontSize=9.5, textColor=MUTED, leading=14)
    foot = ParagraphStyle("foot", parent=styles["Normal"], fontName="Helvetica",
                         fontSize=8, textColor=MUTED, leading=11)

    story = []
    story.append(Paragraph("RailSetu", h_brand))
    story.append(Paragraph(f"{train.number} &nbsp; {train.name}", h_title))

    src = train.source.name if train.source_id else "—"
    dst = train.destination.name if train.destination_id else "—"
    meta = f"{src} &rarr; {dst}"
    if train.train_type:
        meta += f" &nbsp;|&nbsp; {train.train_type}"
    meta += f" &nbsp;|&nbsp; Runs: {_run_days(train.runs_on)}"
    story.append(Paragraph(meta, sub))
    story.append(Spacer(1, 8))

    head = ["#", "Station", "Code", "Arr", "Dep", "Halt", "Day", "PF"]
    rows = [head]
    stops = train.stops.select_related("station").order_by("sequence")
    for i, s in enumerate(stops, start=1):
        rows.append([
            str(i),
            (s.station.name if s.station_id else "")[:32],
            s.station_id or "",
            _hhmm(s.arrival),
            _hhmm(s.departure),
            _halt(s.arrival, s.departure),
            str((s.day_offset or 0) + 1),
            str(platform_for(train.number, s.station_id)),
        ])

    table = Table(rows, repeatRows=1, colWidths=[
        10 * mm, 58 * mm, 16 * mm, 16 * mm, 16 * mm, 18 * mm, 12 * mm, 12 * mm
    ])
    style = [
        ("BACKGROUND", (0, 0), (-1, 0), NAVY),
        ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
        ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
        ("FONTSIZE", (0, 0), (-1, -1), 8.5),
        ("FONTNAME", (0, 1), (-1, -1), "Helvetica"),
        ("TEXTCOLOR", (0, 1), (-1, -1), NAVY),
        ("ALIGN", (0, 0), (0, -1), "CENTER"),
        ("ALIGN", (2, 0), (-1, -1), "CENTER"),
        ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
        ("TOPPADDING", (0, 0), (-1, -1), 5),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 5),
        ("LEFTPADDING", (1, 0), (1, -1), 8),
        ("LINEBELOW", (0, 0), (-1, -1), 0.4, LINE),
    ]
    # first/last stop emphasis
    style.append(("FONTNAME", (1, 1), (1, 1), "Helvetica-Bold"))
    style.append(("FONTNAME", (1, -1), (1, -1), "Helvetica-Bold"))
    for r in range(1, len(rows)):
        if r % 2 == 0:
            style.append(("BACKGROUND", (0, r), (-1, r), SOFT))
    table.setStyle(TableStyle(style))
    story.append(table)

    story.append(Spacer(1, 10))
    story.append(Paragraph(
        "Generated by RailSetu. Schedule is from a static demonstration dataset and "
        "may not reflect current timings. Not an official Indian Railways document.",
        foot,
    ))

    doc.build(story)
    buf.seek(0)
    return buf.read()


class SchedulePdfView(APIView):
    permission_classes = [AllowAny]

    def get(self, request, number):
        try:
            train = Train.objects.select_related("source", "destination").get(number=number)
        except Train.DoesNotExist:
            return HttpResponse("Train not found.", status=404)
        pdf = build_schedule_pdf(train)
        resp = HttpResponse(pdf, content_type="application/pdf")
        resp["Content-Disposition"] = f'attachment; filename="RailSetu_{train.number}_schedule.pdf"'
        return resp