# Generated by Django 5.2.15 on 2026-06-14 16:40

import apps.booking.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stations', '0001_initial'),
        ('trains', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pnr', models.CharField(default=apps.booking.models.generate_pnr, editable=False, max_length=10, unique=True)),
                ('journey_date', models.DateField()),
                ('travel_class', models.CharField(choices=[('1A', 'AC First Class'), ('2A', 'AC 2 Tier'), ('3A', 'AC 3 Tier'), ('SL', 'Sleeper'), ('CC', 'AC Chair Car'), ('2S', 'Second Sitting')], max_length=2)),
                ('quota', models.CharField(choices=[('GN', 'General'), ('TQ', 'Tatkal'), ('LD', 'Ladies'), ('SS', 'Senior Citizen')], default='GN', max_length=2)),
                ('status', models.CharField(choices=[('CNF', 'Confirmed'), ('RAC', 'Reservation Against Cancellation'), ('WL', 'Waitlisted'), ('CAN', 'Cancelled')], default='WL', max_length=3)),
                ('total_fare', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('booked_at', models.DateTimeField(auto_now_add=True)),
                ('from_station', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings_from', to='stations.station')),
                ('to_station', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings_to', to='stations.station')),
                ('train', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='trains.train')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-booked_at'],
            },
        ),
        migrations.CreateModel(
            name='BookedPax',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('age', models.PositiveSmallIntegerField()),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1)),
                ('coach', models.CharField(blank=True, max_length=10)),
                ('berth', models.CharField(blank=True, max_length=20)),
                ('status', models.CharField(choices=[('CNF', 'Confirmed'), ('RAC', 'Reservation Against Cancellation'), ('WL', 'Waitlisted'), ('CAN', 'Cancelled')], default='WL', max_length=3)),
                ('booked_status', models.CharField(blank=True, max_length=12)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='passengers', to='booking.booking')),
            ],
        ),
        migrations.CreateModel(
            name='Passenger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('age', models.PositiveSmallIntegerField()),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_passengers', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['pnr'], name='booking_boo_pnr_301945_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['user', '-booked_at'], name='booking_boo_user_id_b4a930_idx'),
        ),
    ]
