# Generated by Django 5.2.15 on 2026-06-14 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Station',
            fields=[
                ('code', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('zone', models.CharField(blank=True, max_length=10)),
                ('state', models.CharField(blank=True, max_length=60)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
            ],
            options={
                'ordering': ['name'],
                'indexes': [models.Index(fields=['name'], name='stations_st_name_1d3a22_idx')],
            },
        ),
    ]
